# Generated by Django 5.0 on 2023-12-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_status_likes_alter_status_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='ai_summary',
            field=models.TextField(default=''),
        ),
    ]
